CREATE DATABASE PAYROLL_DB;

USE DATABASE PAYROLL_DB;

CREATE SCHEMA HR;

USE SCHEMA HR;

CREATE TABLE EMPLOYEE_MASTER (
    EMPID NUMBER,
    FIRSTNAME VARCHAR,
    LASTNAME VARCHAR,
    STARTDATE DATE,
    EXITDATE DATE,
    TITLE VARCHAR,
    DEPARTMENTTYPE VARCHAR,
    GENDERCODE VARCHAR,
    PERFORMANCE_SCORE VARCHAR
);
