-- Total Employees

SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE_MASTER;

-- Terminated Employees

SELECT COUNT(*) AS TERMINATED_EMPLOYEES
FROM EMPLOYEE_MASTER
WHERE EMPLOYEESTATUS = 'Terminated';

-- Job Title Distribution

SELECT
    TITLE,
    COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEE_MASTER
GROUP BY TITLE
ORDER BY EMPLOYEE_COUNT DESC;

-- Department Distribution

SELECT
    DEPARTMENTTYPE,
    COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEE_MASTER
GROUP BY DEPARTMENTTYPE
ORDER BY EMPLOYEE_COUNT DESC;

-- Gender Distribution

SELECT
    GENDERCODE,
    COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEE_MASTER
GROUP BY GENDERCODE;
